### ISSUE TITLE
reduceSimMatrix appears to apply threshold wrong way around?

### ISSUE THREAD

**Issue by aedanr** [ssayols/rrvgo#1]
Hi,

I'm having an issue with `reduceSimMatrix()`, where it seems to remove more terms when the threshold is higher, when it should be the opposite. The help for the function says that it removes terms "with a similarity higher than 'threshold'" - so setting a higher threshold should remove fewer terms.

The help also says that the output is a data frame with "all terms and it's "reducer" (NA if the term was not reduced)", but there are no NAs. I've assumed that the "parent" column identifies the term that each given term will be collapsed into, so that if I want to remove redundant terms, I should remove all those for which `reducedTerms$go != reducedTerms$parent`. Is this right?

Using the example from the help:
```
go_analysis <- read.delim(system.file("extdata/example.txt", package="rrvgo"))
simMatrix <- calculateSimMatrix(go_analysis$ID, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
scores <- setNames(-log10(go_analysis$qvalue), go_analysis$ID)
reducedTerms <- reduceSimMatrix(simMatrix, scores, threshold=0.7, orgdb="org.Hs.eg.db")
```
`dim(reducedTerms)` gives `128 8`, and `dim(reducedTerms[which(reducedTerms$go == reducedTerms$parent), ])` gives `16 8`, and there are 16 values for `reducedTerms$cluster`. I take this to mean that the 128 terms have been reduced to 16.

But if I change the value of `threshold` to 0.5, `dim(reducedTerms[which(reducedTerms$go == reducedTerms$parent), ])` gives `24 8`, and there are 24 values for `reducedTerms$cluster`. So using a lower threshold seems to produce more clusters, i.e. removes fewer terms.

Is this an error, or have I misinterpreted something?

Thanks,
Aedan

**Comment by ssayols** [comment]
Hi Aedan,
the documentation certainly needs a revision. We changed the algorithm without reflecting it in the help.

Currently, rrvgo uses the similarity between pairs of terms to compute a distance matrix, defined as `(1-simMatrix)`. The terms are then hierarchically clustered using _complete_ linkage, and the tree is cut at the desired threshold, picking the term with the highest score as the representative of each group.

Therefore, higher thresholds lead to fewer groups, and the threshold should be read as the expected similarity of terms within a group (though this is not entirely correct, and you'll see similarities below this threshold being put in the same group).

Also, as you point out, there's no NA anymore and the group representative is also given a parent, which is the very same term. Therefore, as you perfectly assumed, redundant terms are those which `reducedTerms$go != reducedTerms$parent`.

I'll roll out a patch to fix the documentation accordingly.

Thanks,
Sergi

**Comment by aedanr** [comment]
Ok, great. Thanks for clarifying.

**Comment by ssayols** [comment]
updated the documentation accordingly in #d9684f02b2068a85ce518fbf5421e9e12d304a88
