### ISSUE TITLE
shows warnings when using `scatterPlot()`

### ISSUE THREAD

**Issue by kkami1115** [ssayols/rrvgo#13]
HI, I've encountered this warnings in `scatterPlot()`

```
> scatterPlot(simMatrix, reducedTerms)
Warning messages:
1: It is deprecated to specify `guide = FALSE` to remove a guide. Please use `guide = "none"` instead. 
2: It is deprecated to specify `guide = FALSE` to remove a guide. Please use `guide = "none"` instead. 
```
It's not a fatal error so I think you don't need to rush, but it would be nice if you fix it.

Thanks, @kkami1115

**Comment by ssayols** [comment]
Fixed in 1.5.4, code available in Github and in the next Bioconductor release.
Thank you for reporting the issue!
