### ISSUE TITLE
Cannot send `title` parameter to treemap::treemap()

### ISSUE THREAD

**Issue by kkami1115** [ssayols/rrvgo#14]
When I tried to write the title in `treemapPlot()`, I encountered this errror.

```
for (k in c("BP", "CC", "MF")) {
 treemapPlot(reducedTerms =  SomeData[[k]],
             title = paste0(SomeName, k) )
     }
}
```

```
Error in treemap::treemap(reducedTerms, index = c("parentTerm", "term"),  : 
  formal argument "title" matched by multiple actual arguments
```
Looking at the `treemapPlot()` function, it seems to be caused by a conflict with ` title = ""` , which is set the title is none .
First of all, please tell me why it is implemented like this. Secondly, please help me figure out a solution to this error.

Thanks in advance.

**Comment by kkami1115** [comment]
Wops! Sorry, It's fixed in GitHub.
I'm waiting the next release...!

**Comment by ssayols** [comment]
Hey yes, it's fixed in 99a4d28600c0c7dfb87f990606471b6390a8baa2
It's already available in the latest release of Bioconductor 3.14, which you can install from R 4.1.1 and 4.1.2 with `BiocManager::install()`. For older versions of R, install directly from Github with `devtools::install_github("ssayols/rrvgo")`.

**Comment by kkami1115** [comment]
Due to some complications, I'm writing the script in a server environment instead of R in a local environment. 

So They need to update R as soon as possible or install it from GitHub...

**Comment by ssayols** [comment]
Package installation falls back to the user's home when you have no permission to write to the system library (which may be the case in your server). Like this, users have their private libraries without interfering with other users.

In any case, copy-pasting the aforementioned code will always work.

**Comment by kkami1115** [comment]
Yes, It seems that copying and overwriting is the most cost-cutting way. 
I'm sorry my misunderstanding for this issue.
Anyway, thank you for responding.
