### ISSUE TITLE
Reactome, Dorothea, GSEA 

### ISSUE THREAD

**Issue by Tommaso12** [ssayols/rrvgo#16]
Hello, do you think it's possible to use the code also with other databases sources? Thank you a lot!

**Comment by ssayols** [comment]
Hi Tommaso,
`rrvgo` relies on the `GOSemSim` package to compute the semantic similarity among GO terms. In principle, only GO is supported.
But if you could come with a matrix of similarities between your terms, then all subsequent steps in `rrvgo` can be applied to this matrix (eg. `reduceSimMatrix()` and all plotting functions).
Maybe Guangchuang Yu's summary workflow, which is splendidly depicting the usual workflow for gene set enrichment/overrepresentation analysis, may give you an idea of how such matrix could be achieved for databases other than GO (like Kegg, MSigDb, and others).

**Comment by Tommaso12** [comment]
Thanks a lot for the reply and the link! Will have a look!
