### ISSUE TITLE
reduceSimMatrix

### ISSUE THREAD

**Issue by Tima-Ze** [ssayols/rrvgo#20]
![dendogram_dissimilarity matrix](https://github.com/ssayols/rrvgo/assets/76562916/b43e3650-25e3-4e71-99a9-97d6b2cea4bb)
Hi Sergi,
Regarding `reduceSimMatrix()` function
```
function (simMatrix, scores = c("uniqueness", "size"), threshold = 0.7, 
          orgdb, keytype = "ENTREZID") 
```
According to the manual [document](http://bioconductor.riken.jp/packages/3.12/bioc/vignettes/rrvgo/inst/doc/rrvgo.html#session-info) the threshold actually determines/represents the similarity. However, it seems the opposite to be the case.  In the source code :
`cluster <- cutree(hclust(as.dist(1 - simMatrix), method), h = threshold)`,  where the threshold is based on dissimilarity matrix, so lower thresholds indicate a greater similarity between clusters.
Am I right, or did I just get misunderstood? 
Best,
Tima

**Comment by ssayols** [comment]
Hi Tima,
right, thank you for noticing this. We changed the algorithm sometime ago and didn't reflect the changes in the vignette.
I fixed it in a75afc9c6a79a07abb7dbfb2623230acd019588b, hopefully it is clear now.

The right meaning of the threshold parameter should be _`reduceSimMatrix` groups terms with a similarity below `threshold`_

You can fetch the changes from github (`devtools::install_github("ssayols/rrvgo") or from the [Bioconductor devel branch](https://bioconductor.org/packages/devel/bioc/html/rrvgo.html) which I guess will be available in a couple of days.
