### ISSUE TITLE
How to use output from EnrichR?

### ISSUE THREAD

**Issue by TerezaClarence** [ssayols/rrvgo#21]

**Comment by ssayols** [comment]
Hi Tereza,
getting the list of redundant terms is a 2-step procedure, starting with calculating the matrix of similarities between terms. 

Assuming your data.frame is called `x` and your organism is Hsapiens, and the column term contains valid GO identifiers in the for of `GO:0000070`:
```R
simMatrix <- calculateSimMatrix(x$Term, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
```
And then calculating which terms are redundant, using for instance the adjusted p-value as the priority score:
```R
scores <- setNames(-log10(x$Adjusted.P.value), go_analysis$Term)
reducedTerms <- reduceSimMatrix(simMatrix, scores, threshold=0.7, orgdb="org.Hs.eg.db")
```

From here you can play with the visualizations that `rrvgo` offers, or shortlist from your original data.frame the set of terms which are not redundant:
```R
x.non.redundant <- x[x$Term %in% reducedTerms$parent, ]
```

Hope this helps.
Sergi
