### ISSUE TITLE
Axis titles

### ISSUE THREAD

**Issue by sophie-03** [ssayols/rrvgo#25]
Hello, I have made a scatterplot using rrvgo with the following code in R:

`simMatrixBP <- calculateSimMatrix(ora_overlap$ID,
                                orgdb="org.Mmu.eg.db",
                                ont="BP",
                                method="Rel")`

`reducedTermsBP <- reduceSimMatrix(simMatrixBP,
                                #scores,
                                threshold=0.5,
                                orgdb="org.Mmu.eg.db")`

`BP <- scatterPlot(simMatrixBP, reducedTermsBP)`

I want to include axis titles in my plot, but I am unsure what the axes represent. I understand that the axes show the first two components of applying PCoA to the (di)similarity matrx. So would it be appropriate to label the x axis "PC 1" and the y axis "PC 2"? 
And would this be the correct way to include axis in the plot:

`BP <- scatterPlot(simMatrixBP, reducedTermsBP) + 
  theme_classic() + 
  labs( x="PC 1", y = "PC 2) + 
  scale_x_continuous(name=waiver())`

**Comment by ssayols** [comment]
Hi there, yes using "PC 1" and "PC 2" would be appropriate. They stand for "Principal Coordinate [12]".
The function `scatterPlot()` returns a ggplot object. Therefore, you can combine it with any ggplot2 layer of your choice (like you're correctly doing with `theme_classic()` or `labs()` or `scale_x_...()`)
