### ISSUE TITLE
Change color of bubbles in scatterPlot()

### ISSUE THREAD

**Issue by abrantesas** [ssayols/rrvgo#27]
Hello,
Thanks for the package, I am trying to use your scatterPlot for a publication.
I would like to be able to change the colors of the bubbles. I can add a column to the reducedTerms data frame or directly to the object$data created by scatterPlot(). I can't seem to figure out how to use this column I added instead of the parentTerm column. Any tips?
Thanks!
Anthony

**Comment by ssayols** [comment]
Hi Anthony,
`scatterPlot()` returns a ggplot object which you can easily manipulate like.
For instance you can replace the layer with the points with your own (ie. which would select a different column for coloring).

The example below adds a new column for the color annotation called `new_column`, removes the default layer of points colored by `parentTerm`, and adds a new layer of points colored by the `new_column`:

```R
library(rrvgo)
library(ggplot2)

# reduce terms
go_analysis <- read.delim(system.file("extdata/example.txt", package="rrvgo"))
simMatrix <- calculateSimMatrix(go_analysis$ID, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
scores <- setNames(-log10(go_analysis$qvalue), go_analysis$ID)
reducedTerms <- reduceSimMatrix(simMatrix, scores, threshold=0.7, orgdb="org.Hs.eg.db")

# visualize as a scatter plot
p <- scatterPlot(simMatrix, reducedTerms)
p$data$new_column <- factor(sample(1:5, nrow(p$data), replace=TRUE))   # add a new column that I'll use for coloring the points
p$layers[1] <- NULL                                           # remove the points layer
p <- p + geom_point(aes(color=new_column, size=score), alpha=1/2)  # add the new points layer colored by new_column
plot(p)
```

Please reopen the ticket if this is not helpful.
