### ISSUE TITLE
Error in hclust(as.dist(1 - simMatrix)) :    NA/NaN/Inf in foreign function call (arg 10)

### ISSUE THREAD

**Issue by gaelanm** [ssayols/rrvgo#3]
Hello again,

I have managed to form the simMatrix, however, trying to reduce the terms results in the error of the issue title. I have been trying to explore simMatrix for what could be causing this but there appears to be no nan or inf values within the matrix. The similarity matrix and distance matrix seem to be outputting the proper information, and I can even use heatmapPlot() on the raw similarity matrix without any problems. I have looked through the documentation for semantic reduction, but have not been able to find any information that might explain why I am getting this error.

One interesting thing I did find was that if I check the dimensions of 1-simMatrix, it returns NULL. It is also a dist class, but I am assuming that is how the algorithm is supposed to work.

Any help would be appreciated! I am still learning R from using python, and so a lot of these challenges are not very intuitive.

**Comment by ssayols** [comment]
Hi @gaelanm,
I will need a bit more info to debug your issue.  Both `simMatrix` and `1-simMatrix` should be a 2-dimentional squared matrix with length equal (or at least similar) to the number of GO terms you're trying to reduce. So, if they're not a matrix, it probably means the provided GO IDs are not annotated in the Orgdb, either because the organism doesn't match, or the Orgdb doesn't contain GO annotation at all.

May I ask you to provide the vector of GO IDs that you're trying to reduce, and the parameters you're using to call `calculateSimMatrix()`?

**Comment by gaelanm** [comment]
[dataset_A_GOBP_05-10-2020.txt](https://github.com/ssayols/rrvgo/files/5328111/dataset_A_GOBP_05-10-2020.txt)

I have attached the text file I am using. 

go_analysis <- read.delim("dataset_A_GOBP_05-10-2020.txt")

simMatrix <- calculateSimMatrix(go_analysis$ID,
                                orgdb="org.Hs.eg.db",
                                ont="BP",
                                method="Rel")

**Comment by ssayols** [comment]
There was a problem in `reduceSimMatrix()` when no scores were provided.
Fixed in 86f02daf1df1ad060d7e76fafc881274db42b16f.
Please install the latest version from github until the patch is available in the Bioconductor channel (you'll need the `devtools` package for that).

```R
devtools::install_github("https://github.com/ssayols/rrvgo/")
```
Sorry for the inconvenience!

**Comment by gaelanm** [comment]
Wonderful, thank you for all of your help and I look forward to exploring your tools!

**Comment by gaelanm** [comment]
Hey, I just tried redownloading using the above command which worked, but I am unfortunately getting the same error:

Error in hclust(as.dist(1 - simMatrix)) : 
  NA/NaN/Inf in foreign function call (arg 10)

**Comment by ssayols** [comment]
does a `sessionInfo()` tell you that `rrvgo_1.1.2` is attached? If it reports an older version, you need to quit and start R again to load the patched version you just installed from github (or if you already did so, troubleshoot with the `devtools::install_github()` call).
The first few lines of the `reduceSimMatrix()` function should now look like this:
```R
function (simMatrix, scores = NULL, threshold = 0.7, orgdb) 
{
    if (!is.null(scores) && !all(rownames(simMatrix) %in% names(scores))) {
        stop("scores vector does not contain all terms in the similarity matrix")
    }
    sizes <- getGoSize(rownames(simMatrix), orgdb)
    if (is.null(scores)) {
        scores <- sizes
    }
    scores <- scores[match(rownames(simMatrix), names(scores))]
<...>
```
This is the sequence of commands I'm running with your vector of GO terms, which seems to work for me:
```R
library(rrvgo)
x <- read.delim("dataset_A_GOBP_05-10-2020.txt")
s <- calculateSimMatrix(x$ID, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
r <- reduceSimMatrix(s, orgdb="org.Hs.eg.db")
treemapPlot(r)
scatterPlot(s, r)
```
Please let me know if this also worked for you.

**Comment by gaelanm** [comment]
This absolutely works! The issue was just that I needed to restart R after downloading the update which I am kind of embarrassed that I didn't think to do first. But this is now working and generating the proper images. Thank you for the support.
