### ISSUE TITLE
scatterplot ggplot object functionalities seem missing

### ISSUE THREAD

**Issue by eliotbehr** [ssayols/rrvgo#5]
When making scatterplot, which is a ggplot object, I'm unable to add scale titles with the usual "+ labs(x="",y="")" functionality of ggplot. Could you please guide me how to display axis scales, titles (I want to label it as semantic space x, y), make a title of the plot, and show a legend indicating the meaning of colors and size of each bubble on the scatterplot (e.g. what pvalue it is). I've looked in the help documentation for scatterplots, but do not see any arguments I could directly put in there.

Thank you, this software is very helpful for my bioinformatics manuscript.

**Comment by eliotbehr** [comment]
It seems that "ggtitle" works with the scatterplot object, but the "labs" and adding legend functionality are not functional

**Comment by ssayols** [comment]
Hi @eliotbehr,
I'm glad that you find this tool useful. 
Just for completeness, the `scatterPlot()` function produces a `ggplot` grob, which you can then add any layer you like:

```R
R> go_analysis <- read.delim(system.file("extdata/example.txt", package="rrvgo"))
R> simMatrix <- calculateSimMatrix(go_analysis$ID, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
R> scores <- setNames(-log10(go_analysis$qvalue), go_analysis$ID)
R> reducedTerms <- reduceSimMatrix(simMatrix, scores, threshold=0.7, orgdb="org.Hs.eg.
R> p <- scatterPlot(simMatrix, reducedTerms)
```
From here, you could change, for instance, the default theme or add a title:
```R
R> p + theme_classic() + labs(title="the title")
```
The issue with the axis titles is that the `scatterPlot()` function re-defines and disables them. To enable them again, simply add the like this:
```R
R> p + theme_classic() + labs(title="the title", x="the x axis") + scale_x_continuous(name=waiver())
```
And the same for the y-axis.
Hope this helps!

**Comment by eliotbehr** [comment]
Thank you so much! Is there any way to add a legend as well to the rrvgo
ggplot grob, whether for color or size as the REVIGO script does?

**Comment by ssayols** [comment]
The idea is the same, simply add the guides:
```R
R> p +
+      ggplot2::scale_color_discrete(guide="legend") +
+      ggplot2::scale_size_continuous(guide="legend", range=c(0, 25))
```
You can get an idea of what and how ggplot2 layers are being added by `scatterPlot()` by typing the function name without parenthesis:
```R
R> rrvgo::scatterPlot

function (simMatrix, reducedTerms, size = "score", addLabel = TRUE, 
    labelSize = 3) 
{
    if (!all(sapply(c("ggplot2", "ggrepel"), requireNamespace, 
        quietly = TRUE))) {
        stop("Packages ggplot2, ggrepel and/or its dependencies not available. ", 
            "Consider installing them before using this function.", 
            call. = FALSE)
    }
    x <- cmdscale(as.matrix(as.dist(1 - simMatrix)), eig = TRUE, 
        k = 2)
    df <- cbind(as.data.frame(x$points), reducedTerms[match(rownames(x$points), 
        reducedTerms$go), c("term", "parent", "parentTerm", "size")])
    p <- ggplot2::ggplot(df, ggplot2::aes(x = V1, y = V2, color = parentTerm)) + 
        ggplot2::geom_point(ggplot2::aes(size = size), alpha = 0.5) + 
        ggplot2::scale_color_discrete(guide = FALSE) + ggplot2::scale_size_continuous(guide = FALSE, 
        range = c(0, 25)) + ggplot2::scale_x_continuous(name = "") + 
        ggplot2::scale_y_continuous(name = "") + ggplot2::theme_minimal() + 
        ggplot2::theme(axis.text.x = ggplot2::element_blank(), 
            axis.text.y = ggplot2::element_blank())
    if (addLabel) {
        p + ggrepel::geom_label_repel(aes(label = parentTerm), 
            data = subset(df, parent == rownames(df)), box.padding = grid::unit(1, 
                "lines"), size = labelSize)
    }
    else {
        p
    }
}
<bytecode: 0x5589d6424e50>
<environment: namespace:rrvgo>
```
Here you see the default theme being changed, the axis titles disabled, the legends taken out, etc.
