### ISSUE TITLE
"frequency", "uniqueness" or "dispensability" terms

### ISSUE THREAD

**Issue by tech-niche3** [ssayols/rrvgo#9]
I am searching a way to use your R package to retrieve "frequency", "uniqueness" or "dispensability" terms as the web-tool does. Will there be an update to provide this?

**Comment by ssayols** [comment]
Currently it's not possible. We have plans to include such metrics, but realistically we won't have such functionality available before the next Bioconductor release scheduled for October.

Sorry for the inconvenience. I'll leave the issue open so you get some feedback as soon as it's ready.

**Comment by ssayols** [comment]
The "uniqueness" and "dispensability" of a term are now included in the output of `reduceSimMatrix()`. There's no plans to include a "frequency" term in the near future.
To use the new features, you can install the package from github, or wait until the next Bioconductor release (3.18)
